using TagTool.Cache;
using TagTool.Tags;

namespace TagTool.Scripting
{
    [TagStructure(Size = 0x2)]
    public class HsType : TagStructure
	{
        [TagField(MinVersion = CacheVersion.Halo3Alpha, MaxVersion = CacheVersion.Halo3Alpha)]
        public Halo3AlphaValue Halo3Alpha;

        [TagField(MinVersion = CacheVersion.Halo3Beta, MaxVersion = CacheVersion.Halo3Beta)]
        public Halo3BetaValue Halo3Beta;

        [TagField(MinVersion = CacheVersion.Halo3Retail, MaxVersion = CacheVersion.Halo3Retail)]
        public Halo3RetailValue Halo3Retail;

        [TagField(MinVersion = CacheVersion.Halo3ODST, MaxVersion = CacheVersion.Halo3ODST)]
        public Halo3ODSTValue Halo3ODST;

        [TagField(MinVersion = CacheVersion.HaloOnlineED, MaxVersion = CacheVersion.HaloOnline700123)] //Changed max version to 700123 - Faber
        public HaloOnlineValue HaloOnline;

        [TagField (MinVersion = CacheVersion.HaloReach11883, MaxVersion = CacheVersion.HaloReach11883)]
        public HaloReach11883Value HaloReach11883;

        [TagField(MinVersion = CacheVersion.HaloReachBeta, MaxVersion = CacheVersion.HaloReachBeta)]
        public HaloReachBetaValue HaloReachBeta;

        [TagField(MinVersion = CacheVersion.HaloReach)]
        public HaloReachValue HaloReach;

        public enum Halo3AlphaValue : ushort //currently guesswork/placeholder - Faber
        {
            Invalid = 47802,
            Unparsed = 0,
            SpecialForm,
            FunctionName,
            Passthrough,
            Void,
            Boolean,
            Real,
            Short,
            Long,
            String,
            Script,
            StringId,
            UnitSeatMapping,
            TriggerVolume,
            CutsceneFlag,
            CutsceneCameraPoint,
            CutsceneTitle,
            CutsceneRecording,
            DeviceGroup,
            Ai,
            AiCommandList,
            AiCommandScript,
            AiBehavior,
            AiOrders,
            AiLine,
            StartingProfile,
            Conversation,
            ZoneSet,
            DesignerZone,
            PointReference,
            Style,
            ObjectList,
            Folder,
            Sound,
            Effect,
            Damage,
            LoopingSound,
            AnimationGraph,
            DamageEffect,
            ObjectDefinition,
            Bitmap,
            Shader,
            RenderModel,
            StructureDefinition,
            LightmapDefinition,
            CinematicDefinition,
            CinematicSceneDefinition,
            BinkDefinition,
            AnyTag,
            AnyTagNotResolving,
            GameDifficulty,
            Team,
            MpTeam,
            Controller,
            ButtonPreset,
            JoystickPreset,
            PlayerColor,
            PlayerCharacterType,
            VoiceOutputSetting,
            VoiceMask,
            SubtitleSetting,
            ActorType,
            ModelState,
            Event,
            CharacterPhysics,
            Object,
            Unit,
            Vehicle,
            Weapon,
            Device,
            Scenery,
            EffectScenery,
            ObjectName,
            UnitName,
            VehicleName,
            WeaponName,
            DeviceName,
            SceneryName,
            EffectSceneryName,
            CinematicLightprobe,
            AnimationBudgetReference,
            LoopingSoundBudgetReference,
            SoundBudgetReference
        }

        public enum Halo3BetaValue : ushort //currently guesswork/placeholder - Faber
        {
            Invalid = 47802,
            Unparsed = 0,
            SpecialForm,
            FunctionName,
            Passthrough,
            Void,
            Boolean,
            Real,
            Short,
            Long,
            String,
            Script,
            StringId,
            UnitSeatMapping,
            TriggerVolume,
            CutsceneFlag,
            CutsceneCameraPoint,
            CutsceneTitle,
            CutsceneRecording,
            DeviceGroup,
            Ai,
            AiCommandList,
            AiCommandScript,
            AiBehavior,
            AiOrders,
            AiLine,
            StartingProfile,
            Conversation,
            ZoneSet,
            DesignerZone,
            PointReference,
            Style,
            ObjectList,
            Folder,
            Sound,
            Effect,
            Damage,
            LoopingSound,
            AnimationGraph,
            DamageEffect,
            ObjectDefinition,
            Bitmap,
            Shader,
            RenderModel,
            StructureDefinition,
            LightmapDefinition,
            CinematicDefinition,
            CinematicSceneDefinition,
            BinkDefinition,
            AnyTag,
            AnyTagNotResolving,
            GameDifficulty,
            Team,
            MpTeam,
            Controller,
            ButtonPreset,
            JoystickPreset,
            PlayerColor,
            PlayerCharacterType,
            VoiceOutputSetting,
            VoiceMask,
            SubtitleSetting,
            ActorType,
            ModelState,
            Event,
            CharacterPhysics,
            Object,
            Unit,
            Vehicle,
            Weapon,
            Device,
            Scenery,
            EffectScenery,
            ObjectName,
            UnitName,
            VehicleName,
            WeaponName,
            DeviceName,
            SceneryName,
            EffectSceneryName,
            CinematicLightprobe,
            AnimationBudgetReference,
            LoopingSoundBudgetReference,
            SoundBudgetReference
        }
        public enum Halo3RetailValue : ushort
        {
            Invalid = 47802,
            Unparsed = 0,
            SpecialForm,
            FunctionName,
            Passthrough,
            Void,
            Boolean,
            Real,
            Short,
            Long,
            String,
            Script,
            StringId,
            UnitSeatMapping,
            TriggerVolume,
            CutsceneFlag,
            CutsceneCameraPoint,
            CutsceneTitle,
            CutsceneRecording,
            DeviceGroup,
            Ai,
            AiCommandList,
            AiCommandScript,
            AiBehavior,
            AiOrders,
            AiLine,
            StartingProfile,
            Conversation,
            ZoneSet,
            DesignerZone,
            PointReference,
            Style,
            ObjectList,
            Folder,
            Sound,
            Effect,
            Damage,
            LoopingSound,
            AnimationGraph,
            DamageEffect,
            ObjectDefinition,
            Bitmap,
            Shader,
            RenderModel,
            StructureDefinition,
            LightmapDefinition,
            CinematicDefinition,
            CinematicSceneDefinition,
            BinkDefinition,
            AnyTag,
            AnyTagNotResolving,
            GameDifficulty,
            Team,
            MpTeam,
            Controller,
            ButtonPreset,
            JoystickPreset,
            PlayerColor,
            PlayerCharacterType,
            VoiceOutputSetting,
            VoiceMask,
            SubtitleSetting,
            ActorType,
            ModelState,
            Event,
            CharacterPhysics,
            Object,
            Unit,
            Vehicle,
            Weapon,
            Device,
            Scenery,
            EffectScenery,
            ObjectName,
            UnitName,
            VehicleName,
            WeaponName,
            DeviceName,
            SceneryName,
            EffectSceneryName,
            CinematicLightprobe,
            AnimationBudgetReference,
            LoopingSoundBudgetReference,
            SoundBudgetReference
        }

        public enum Halo3ODSTValue : ushort
        {
            Invalid = 47802,
            Unparsed = 0,
            SpecialForm,
            FunctionName,
            Passthrough,
            Void,
            Boolean,
            Real,
            Short,
            Long,
            String,
            Script,
            StringId,
            UnitSeatMapping,
            TriggerVolume,
            CutsceneFlag,
            CutsceneCameraPoint,
            CutsceneTitle,
            CutsceneRecording,
            DeviceGroup,
            Ai,
            AiCommandList,
            AiCommandScript,
            AiBehavior,
            AiOrders,
            AiLine,
            StartingProfile,
            Conversation,
            ZoneSet,
            DesignerZone,
            PointReference,
            Style,
            ObjectList,
            Folder,
            Sound,
            Effect,
            Damage,
            LoopingSound,
            AnimationGraph,
            DamageEffect,
            ObjectDefinition,
            Bitmap,
            Shader,
            RenderModel,
            StructureDefinition,
            LightmapDefinition,
            CinematicDefinition,
            CinematicSceneDefinition,
            BinkDefinition,
            AnyTag,
            AnyTagNotResolving,
            GameDifficulty,
            Team,
            MpTeam,
            Controller,
            ButtonPreset,
            JoystickPreset,
            PlayerColor,
            PlayerCharacterType,
            VoiceOutputSetting,
            VoiceMask,
            SubtitleSetting,
            ActorType,
            ModelState,
            Event,
            CharacterPhysics,
            PrimarySkull,
            SecondarySkull,
            Object,
            Unit,
            Vehicle,
            Weapon,
            Device,
            Scenery,
            EffectScenery,
            ObjectName,
            UnitName,
            VehicleName,
            WeaponName,
            DeviceName,
            SceneryName,
            EffectSceneryName,
            CinematicLightprobe,
            AnimationBudgetReference,
            LoopingSoundBudgetReference,
            SoundBudgetReference
        }

        public enum HaloOnlineValue : ushort
        {
            Invalid = 47802,
            Unparsed = 0,
            SpecialForm,
            FunctionName,
            Passthrough,
            Void,
            Boolean,
            Real,
            Short,
            Long,
            String,
            Script,
            StringId,
            UnitSeatMapping,
            TriggerVolume,
            CutsceneFlag,
            CutsceneCameraPoint,
            CutsceneTitle,
            CutsceneRecording,
            DeviceGroup,
            Ai,
            AiCommandList,
            AiCommandScript,
            AiBehavior,
            AiOrders,
            AiLine,
            StartingProfile,
            Conversation,
            ZoneSet,
            DesignerZone,
            PointReference,
            Style,
            ObjectList,
            Folder,
            Sound,
            Effect,
            Damage,
            LoopingSound,
            AnimationGraph,
            DamageEffect,
            ObjectDefinition,
            Bitmap,
            Shader,
            RenderModel,
            StructureDefinition,
            LightmapDefinition,
            CinematicDefinition,
            CinematicSceneDefinition,
            BinkDefinition,
            AnyTag,
            AnyTagNotResolving,
            GameDifficulty,
            Team,
            MpTeam,
            Controller,
            ButtonPreset,
            JoystickPreset,
            PlayerCharacterType,
            VoiceOutputSetting,
            VoiceMask,
            SubtitleSetting,
            ActorType,
            ModelState,
            Event,
            CharacterPhysics,
            PrimarySkull,
            SecondarySkull,
            Object,
            Unit,
            Vehicle,
            Weapon,
            Device,
            Scenery,
            EffectScenery,
            ObjectName,
            UnitName,
            VehicleName,
            WeaponName,
            DeviceName,
            SceneryName,
            EffectSceneryName,
            CinematicLightprobe,
            AnimationBudgetReference,
            LoopingSoundBudgetReference,
            SoundBudgetReference
        }

        public enum HaloReachValue : ushort //currently guesswork/placeholder - Faber
        {
            //adding values from reach - Faber
            Invalid,
            Unparsed,
            SpecialForm,
            FunctionName,
            Passthrough,
            Void,
            Boolean,
            Real,
            Short,
            Long,
            String,
            Script,
            StringId,
             UnitSeatMapping,
            TriggerVolume,
            CutsceneFlag,
            CutsceneCameraPoint,
            CutsceneTitle,
            CutsceneRecording,
            DeviceGroup,
            Ai,
            AiCommandList,
            AiCommandScript,
            AiBehavior,
            AiOrders,
            AiLine,
            StartingProfile,
            Conversation,
            ZoneSet,
            DesignerZone,
            PointReference,
            Style,
            ObjectList,
            Folder,
            Sound,
            Effect,
            Damage,
            LoopingSound,
            AnimationGraph,
            DamageEffect,
            ObjectDefinition,
            Bitmap,
            Shader,
            RenderModel,
            StructureDefinition,
            LightmapDefinition,
            CinematicDefinition,
            CinematicSceneDefinition,
            BinkDefinition,
            AnyTag,
            AnyTagNotResolving,
            GameDifficulty,
            Team,
            MpTeam,
            Controller,
            ButtonPreset,
            JoystickPreset,
            PlayerColor,
            PlayerCharacterType,
            VoiceOutputSetting,
            VoiceMask,
            SubtitleSetting,
            ActorType,
            ModelState,
            Event,
            CharacterPhysics,
            PrimarySkull,
            SecondarySkull,
            Object,
            Unit,
            Vehicle,
            Weapon,
            Device,
            Scenery,
            EffectScenery,
            ObjectName,
            UnitName,
            VehicleName,
            WeaponName,
            DeviceName,
            SceneryName,
            EffectSceneryName,
            CinematicLightprobe,
            AnimationBudgetReference,
            LoopingSoundBudgetReference,
            SoundBudgetReference
            //Note, this is currently guessing at the values, I will update it when I have the time to look at the values in the reach script files - Faber
        }

        public enum HaloReachBetaValue : ushort //currently guesswork/placeholder - Faber
        {
            //adding values from reach, mostly guess work at the moment until a proper list of scripting functions is found - Faber
            Invalid,
            Unparsed,
            SpecialForm,
            FunctionName,
            Passthrough,
            Void,
            Boolean,
            Real,
            Short,
            Long,
            String,
            Script,
            StringId,
             UnitSeatMapping,
            TriggerVolume,
            CutsceneFlag,
            CutsceneCameraPoint,
            CutsceneTitle,
            CutsceneRecording,
            DeviceGroup,
            Ai,
            AiCommandList,
            AiCommandScript,
            AiBehavior,
            AiOrders,
            AiLine,
            StartingProfile,
            Conversation,
            ZoneSet,
            DesignerZone,
            PointReference,
            Style,
            ObjectList,
            Folder,
            Sound,
            Effect,
            Damage,
            LoopingSound,
            AnimationGraph,
            DamageEffect,
            ObjectDefinition,
            Bitmap,
            Shader,
            RenderModel,
            StructureDefinition,
            LightmapDefinition,
            CinematicDefinition,
            CinematicSceneDefinition,
            BinkDefinition,
            AnyTag,
            AnyTagNotResolving,
            GameDifficulty,
            Team,
            MpTeam,
            Controller,
            ButtonPreset,
            JoystickPreset,
            PlayerColor,
            PlayerCharacterType,
            VoiceOutputSetting,
            VoiceMask,
            SubtitleSetting,
            ActorType,
            ModelState,
            Event,
            CharacterPhysics,
            PrimarySkull,
            SecondarySkull,
            Object,
            Unit,
            Vehicle,
            Weapon,
            Device,
            Scenery,
            EffectScenery,
            ObjectName,
            UnitName,
            VehicleName,
            WeaponName,
            DeviceName,
            SceneryName,
            EffectSceneryName,
            CinematicLightprobe,
            AnimationBudgetReference,
            LoopingSoundBudgetReference,
            SoundBudgetReference
            //Note, this is currently guessing at the values, I will update it when I have the time to look at the values in the reach script files - Faber
        }

        public enum HaloReach11883Value : ushort //currently guesswork/placeholder - Faber
        {
            //adding values from reach, mostly guess work at the moment until a proper list of scripting functions is found - Faber
            Invalid,
            Unparsed,
            SpecialForm,
            FunctionName,
            Passthrough,
            Void,
            Boolean,
            Real,
            Short,
            Long,
            String,
            Script,
            StringId,
             UnitSeatMapping,
            TriggerVolume,
            CutsceneFlag,
            CutsceneCameraPoint,
            CutsceneTitle,
            CutsceneRecording,
            DeviceGroup,
            Ai,
            AiCommandList,
            AiCommandScript,
            AiBehavior,
            AiOrders,
            AiLine,
            StartingProfile,
            Conversation,
            ZoneSet,
            DesignerZone,
            PointReference,
            Style,
            ObjectList,
            Folder,
            Sound,
            Effect,
            Damage,
            LoopingSound,
            AnimationGraph,
            DamageEffect,
            ObjectDefinition,
            Bitmap,
            Shader,
            RenderModel,
            StructureDefinition,
            LightmapDefinition,
            CinematicDefinition,
            CinematicSceneDefinition,
            BinkDefinition,
            AnyTag,
            AnyTagNotResolving,
            GameDifficulty,
            Team,
            MpTeam,
            Controller,
            ButtonPreset,
            JoystickPreset,
            PlayerColor,
            PlayerCharacterType,
            VoiceOutputSetting,
            VoiceMask,
            SubtitleSetting,
            ActorType,
            ModelState,
            Event,
            CharacterPhysics,
            PrimarySkull,
            SecondarySkull,
            Object,
            Unit,
            Vehicle,
            Weapon,
            Device,
            Scenery,
            EffectScenery,
            ObjectName,
            UnitName,
            VehicleName,
            WeaponName,
            DeviceName,
            SceneryName,
            EffectSceneryName,
            CinematicLightprobe,
            AnimationBudgetReference,
            LoopingSoundBudgetReference,
            SoundBudgetReference
            //Note, this is currently guessing at the values, I will update it when I have the time to look at the values in the reach script files - Faber
        }
    [TagEnum(IsVersioned = true)]
    public enum HsType
    {
        [TagEnumMember(Flags = TagEnumMemberFlags.Constant)]
        Invalid = 0xBABA,

        Unparsed = 0,
        SpecialForm,
        FunctionName,
        Passthrough,
        Void,
        Boolean,
        Real,
        Short,
        Long,
        String,
        Script,
        StringId,
        UnitSeatMapping,
        TriggerVolume,
        CutsceneFlag,
        CutsceneCameraPoint,
        CutsceneTitle,
        CutsceneRecording,
        DeviceGroup,
        Ai,
        AiCommandList,
        AiCommandScript,
        AiBehavior,
        AiOrders,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        AiLine,
        StartingProfile,
        Conversation,
        [TagEnumMember(MinVersion = CacheVersion.HaloReach)]
        Player,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        ZoneSet,
        [TagEnumMember(MaxVersion = CacheVersion.Halo2PC)]
        StructureBsp,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        DesignerZone,
        [TagEnumMember(MaxVersion = CacheVersion.Halo2PC)]
        Navpoint,
        PointReference,
        Style,
        [TagEnumMember(MaxVersion = CacheVersion.Halo2PC)]
        HudMessage,
        ObjectList,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Retail)]
        Folder,
        Sound,
        Effect,
        Damage,
        LoopingSound,
        AnimationGraph,
        DamageEffect,
        ObjectDefinition,
        Bitmap,
        Shader,
        RenderModel,
        StructureDefinition,
        LightmapDefinition,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        CinematicDefinition,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        CinematicSceneDefinition,
        [TagEnumMember(MinVersion = CacheVersion.HaloReach)]
        CinematicTransitionDefinition,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Retail)]
        BinkDefinition,
        [TagEnumMember(MinVersion = CacheVersion.HaloReach)]
        CuiScreenDefinition,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        AnyTag,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        AnyTagNotResolving,
        GameDifficulty,
        Team,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        MpTeam,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        Controller,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        ButtonPreset,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        JoystickPreset,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta, MaxVersion = CacheVersion.Halo3ODST)]
        [TagEnumMember(MinVersion = CacheVersion.HaloReach)]
        PlayerColor,
        [TagEnumMember(MinVersion = CacheVersion.HaloReach)]
        PlayerModelChoice,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta, MaxVersion = CacheVersion.HaloOnline700123)]
        PlayerCharacterType,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        VoiceOutputSetting,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        VoiceMask,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        SubtitleSetting,
        ActorType,
        [TagEnumMember(MaxVersion = CacheVersion.Halo2PC)]
        HudCorner,
        ModelState,
        [TagEnumMember(MaxVersion = CacheVersion.Halo2PC)]
        NetworkEvent,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        Event,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        CharacterPhysics,
        [TagEnumMember(MinVersion = CacheVersion.Halo3ODST, MaxVersion = CacheVersion.HaloOnline700123)]
        PrimarySkull,
        [TagEnumMember(MinVersion = CacheVersion.Halo3ODST, MaxVersion = CacheVersion.HaloOnline700123)]
        SecondarySkull,
        [TagEnumMember(MinVersion = CacheVersion.HaloReach)]
        Skull,
        [TagEnumMember(MinVersion = CacheVersion.HaloReach)]
        FiringPointEvaluator,
        [TagEnumMember(MinVersion = CacheVersion.HaloReach)]
        DamageRegion,
        Object,
        Unit,
        Vehicle,
        Weapon,
        Device,
        Scenery,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Retail)]
        EffectScenery,
        ObjectName,
        UnitName,
        VehicleName,
        WeaponName,
        DeviceName,
        SceneryName,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Retail)]
        EffectSceneryName,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Beta)]
        CinematicLightprobe,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Retail)]
        AnimationBudgetReference,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Retail)]
        LoopingSoundBudgetReference,
        [TagEnumMember(MinVersion = CacheVersion.Halo3Retail)]
        SoundBudgetReference,
    }
}
